# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthHiddenService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ControlChannel_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AuthHiddenService.proto',
  package='Protocol.Data.AuthHiddenService',
  serialized_pb=_b('\n\x17\x41uthHiddenService.proto\x12\x1fProtocol.Data.AuthHiddenService\x1a\x14\x43ontrolChannel.proto\"x\n\x06Packet\x12\x35\n\x05proof\x18\x01 \x01(\x0b\x32&.Protocol.Data.AuthHiddenService.Proof\x12\x37\n\x06result\x18\x02 \x01(\x0b\x32\'.Protocol.Data.AuthHiddenService.Result\".\n\x05Proof\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"4\n\x06Result\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x02(\x08\x12\x18\n\x10is_known_contact\x18\x02 \x01(\x08::\n\rclient_cookie\x12\".Protocol.Data.Control.OpenChannel\x18\xa0\x38 \x01(\x0c:<\n\rserver_cookie\x12$.Protocol.Data.Control.ChannelResult\x18\xa0\x38 \x01(\x0c')
  ,
  dependencies=[ControlChannel_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


CLIENT_COOKIE_FIELD_NUMBER = 7200
client_cookie = _descriptor.FieldDescriptor(
  name='client_cookie', full_name='Protocol.Data.AuthHiddenService.client_cookie', index=0,
  number=7200, type=12, cpp_type=9, label=1,
  has_default_value=False, default_value=_b(""),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
SERVER_COOKIE_FIELD_NUMBER = 7200
server_cookie = _descriptor.FieldDescriptor(
  name='server_cookie', full_name='Protocol.Data.AuthHiddenService.server_cookie', index=1,
  number=7200, type=12, cpp_type=9, label=1,
  has_default_value=False, default_value=_b(""),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)


_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='Protocol.Data.AuthHiddenService.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proof', full_name='Protocol.Data.AuthHiddenService.Packet.proof', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='Protocol.Data.AuthHiddenService.Packet.result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=202,
)


_PROOF = _descriptor.Descriptor(
  name='Proof',
  full_name='Protocol.Data.AuthHiddenService.Proof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='Protocol.Data.AuthHiddenService.Proof.public_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Protocol.Data.AuthHiddenService.Proof.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=250,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Protocol.Data.AuthHiddenService.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accepted', full_name='Protocol.Data.AuthHiddenService.Result.accepted', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_known_contact', full_name='Protocol.Data.AuthHiddenService.Result.is_known_contact', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=304,
)

_PACKET.fields_by_name['proof'].message_type = _PROOF
_PACKET.fields_by_name['result'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.message_types_by_name['Proof'] = _PROOF
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.extensions_by_name['client_cookie'] = client_cookie
DESCRIPTOR.extensions_by_name['server_cookie'] = server_cookie

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'AuthHiddenService_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.AuthHiddenService.Packet)
  ))
_sym_db.RegisterMessage(Packet)

Proof = _reflection.GeneratedProtocolMessageType('Proof', (_message.Message,), dict(
  DESCRIPTOR = _PROOF,
  __module__ = 'AuthHiddenService_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.AuthHiddenService.Proof)
  ))
_sym_db.RegisterMessage(Proof)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'AuthHiddenService_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.AuthHiddenService.Result)
  ))
_sym_db.RegisterMessage(Result)

ControlChannel_pb2.OpenChannel.RegisterExtension(client_cookie)
ControlChannel_pb2.ChannelResult.RegisterExtension(server_cookie)

# @@protoc_insertion_point(module_scope)
