# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatChannel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChatChannel.proto',
  package='Protocol.Data.Chat',
  serialized_pb=_b('\n\x11\x43hatChannel.proto\x12\x12Protocol.Data.Chat\"~\n\x06Packet\x12\x35\n\x0c\x63hat_message\x18\x01 \x01(\x0b\x32\x1f.Protocol.Data.Chat.ChatMessage\x12=\n\x10\x63hat_acknowledge\x18\x02 \x01(\x0b\x32#.Protocol.Data.Chat.ChatAcknowledge\"K\n\x0b\x43hatMessage\x12\x14\n\x0cmessage_text\x18\x01 \x02(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\r\x12\x12\n\ntime_delta\x18\x03 \x01(\x03\"=\n\x0f\x43hatAcknowledge\x12\x12\n\nmessage_id\x18\x01 \x01(\r\x12\x16\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08:\x04true')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='Protocol.Data.Chat.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chat_message', full_name='Protocol.Data.Chat.Packet.chat_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chat_acknowledge', full_name='Protocol.Data.Chat.Packet.chat_acknowledge', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=167,
)


_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='Protocol.Data.Chat.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_text', full_name='Protocol.Data.Chat.ChatMessage.message_text', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='Protocol.Data.Chat.ChatMessage.message_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_delta', full_name='Protocol.Data.Chat.ChatMessage.time_delta', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=244,
)


_CHATACKNOWLEDGE = _descriptor.Descriptor(
  name='ChatAcknowledge',
  full_name='Protocol.Data.Chat.ChatAcknowledge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_id', full_name='Protocol.Data.Chat.ChatAcknowledge.message_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accepted', full_name='Protocol.Data.Chat.ChatAcknowledge.accepted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=307,
)

_PACKET.fields_by_name['chat_message'].message_type = _CHATMESSAGE
_PACKET.fields_by_name['chat_acknowledge'].message_type = _CHATACKNOWLEDGE
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['ChatAcknowledge'] = _CHATACKNOWLEDGE

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'ChatChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Chat.Packet)
  ))
_sym_db.RegisterMessage(Packet)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), dict(
  DESCRIPTOR = _CHATMESSAGE,
  __module__ = 'ChatChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Chat.ChatMessage)
  ))
_sym_db.RegisterMessage(ChatMessage)

ChatAcknowledge = _reflection.GeneratedProtocolMessageType('ChatAcknowledge', (_message.Message,), dict(
  DESCRIPTOR = _CHATACKNOWLEDGE,
  __module__ = 'ChatChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Chat.ChatAcknowledge)
  ))
_sym_db.RegisterMessage(ChatAcknowledge)


# @@protoc_insertion_point(module_scope)
