# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContactRequestChannel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ControlChannel_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ContactRequestChannel.proto',
  package='Protocol.Data.ContactRequest',
  serialized_pb=_b('\n\x1b\x43ontactRequestChannel.proto\x12\x1cProtocol.Data.ContactRequest\x1a\x14\x43ontrolChannel.proto\"8\n\x0e\x43ontactRequest\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\x14\n\x0cmessage_text\x18\x02 \x01(\t\"\x96\x01\n\x08Response\x12=\n\x06status\x18\x01 \x02(\x0e\x32-.Protocol.Data.ContactRequest.Response.Status\"K\n\x06Status\x12\r\n\tUndefined\x10\x00\x12\x0b\n\x07Pending\x10\x01\x12\x0c\n\x08\x41\x63\x63\x65pted\x10\x02\x12\x0c\n\x08Rejected\x10\x03\x12\t\n\x05\x45rror\x10\x04*>\n\x06Limits\x12\x19\n\x14MessageMaxCharacters\x10\xd0\x0f\x12\x19\n\x15NicknameMaxCharacters\x10\x1e:j\n\x0f\x63ontact_request\x12\".Protocol.Data.Control.OpenChannel\x18\xc8\x01 \x01(\x0b\x32,.Protocol.Data.ContactRequest.ContactRequest:_\n\x08response\x12$.Protocol.Data.Control.ChannelResult\x18\xc9\x01 \x01(\x0b\x32&.Protocol.Data.ContactRequest.Response')
  ,
  dependencies=[ControlChannel_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_LIMITS = _descriptor.EnumDescriptor(
  name='Limits',
  full_name='Protocol.Data.ContactRequest.Limits',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MessageMaxCharacters', index=0, number=2000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NicknameMaxCharacters', index=1, number=30,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=294,
  serialized_end=356,
)
_sym_db.RegisterEnumDescriptor(_LIMITS)

Limits = enum_type_wrapper.EnumTypeWrapper(_LIMITS)
MessageMaxCharacters = 2000
NicknameMaxCharacters = 30

CONTACT_REQUEST_FIELD_NUMBER = 200
contact_request = _descriptor.FieldDescriptor(
  name='contact_request', full_name='Protocol.Data.ContactRequest.contact_request', index=0,
  number=200, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
RESPONSE_FIELD_NUMBER = 201
response = _descriptor.FieldDescriptor(
  name='response', full_name='Protocol.Data.ContactRequest.response', index=1,
  number=201, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Protocol.Data.ContactRequest.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Undefined', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Pending', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Accepted', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Rejected', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Error', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=217,
  serialized_end=292,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)


_CONTACTREQUEST = _descriptor.Descriptor(
  name='ContactRequest',
  full_name='Protocol.Data.ContactRequest.ContactRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nickname', full_name='Protocol.Data.ContactRequest.ContactRequest.nickname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_text', full_name='Protocol.Data.ContactRequest.ContactRequest.message_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=139,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Protocol.Data.ContactRequest.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Protocol.Data.ContactRequest.Response.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=292,
)

_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE_STATUS.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['ContactRequest'] = _CONTACTREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['Limits'] = _LIMITS
DESCRIPTOR.extensions_by_name['contact_request'] = contact_request
DESCRIPTOR.extensions_by_name['response'] = response

ContactRequest = _reflection.GeneratedProtocolMessageType('ContactRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTREQUEST,
  __module__ = 'ContactRequestChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.ContactRequest.ContactRequest)
  ))
_sym_db.RegisterMessage(ContactRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'ContactRequestChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.ContactRequest.Response)
  ))
_sym_db.RegisterMessage(Response)

contact_request.message_type = _CONTACTREQUEST
ControlChannel_pb2.OpenChannel.RegisterExtension(contact_request)
response.message_type = _RESPONSE
ControlChannel_pb2.ChannelResult.RegisterExtension(response)

# @@protoc_insertion_point(module_scope)
