# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ControlChannel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ControlChannel.proto',
  package='Protocol.Data.Control',
  serialized_pb=_b('\n\x14\x43ontrolChannel.proto\x12\x15Protocol.Data.Control\"\xb8\x02\n\x06Packet\x12\x38\n\x0copen_channel\x18\x01 \x01(\x0b\x32\".Protocol.Data.Control.OpenChannel\x12<\n\x0e\x63hannel_result\x18\x02 \x01(\x0b\x32$.Protocol.Data.Control.ChannelResult\x12\x34\n\nkeep_alive\x18\x03 \x01(\x0b\x32 .Protocol.Data.Control.KeepAlive\x12>\n\x0f\x65nable_features\x18\x04 \x01(\x0b\x32%.Protocol.Data.Control.EnableFeatures\x12@\n\x10\x66\x65\x61tures_enabled\x18\x05 \x01(\x0b\x32&.Protocol.Data.Control.FeaturesEnabled\"I\n\x0bOpenChannel\x12\x1a\n\x12\x63hannel_identifier\x18\x01 \x02(\x05\x12\x14\n\x0c\x63hannel_type\x18\x02 \x02(\t*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"\xff\x01\n\rChannelResult\x12\x1a\n\x12\x63hannel_identifier\x18\x01 \x02(\x05\x12\x0e\n\x06opened\x18\x02 \x02(\x08\x12\x46\n\x0c\x63ommon_error\x18\x03 \x01(\x0e\x32\x30.Protocol.Data.Control.ChannelResult.CommonError\"p\n\x0b\x43ommonError\x12\x10\n\x0cGenericError\x10\x00\x12\x14\n\x10UnknownTypeError\x10\x01\x12\x15\n\x11UnauthorizedError\x10\x02\x12\x11\n\rBadUsageError\x10\x03\x12\x0f\n\x0b\x46\x61iledError\x10\x04*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"\'\n\tKeepAlive\x12\x1a\n\x12response_requested\x18\x01 \x02(\x08\"+\n\x0e\x45nableFeatures\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x03(\t*\x08\x08\x64\x10\x80\x80\x80\x80\x02\",\n\x0f\x46\x65\x61turesEnabled\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x03(\t*\x08\x08\x64\x10\x80\x80\x80\x80\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CHANNELRESULT_COMMONERROR = _descriptor.EnumDescriptor(
  name='CommonError',
  full_name='Protocol.Data.Control.ChannelResult.CommonError',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GenericError', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnknownTypeError', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UnauthorizedError', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BadUsageError', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FailedError', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=571,
  serialized_end=683,
)
_sym_db.RegisterEnumDescriptor(_CHANNELRESULT_COMMONERROR)


_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='Protocol.Data.Control.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='open_channel', full_name='Protocol.Data.Control.Packet.open_channel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel_result', full_name='Protocol.Data.Control.Packet.channel_result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keep_alive', full_name='Protocol.Data.Control.Packet.keep_alive', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_features', full_name='Protocol.Data.Control.Packet.enable_features', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='features_enabled', full_name='Protocol.Data.Control.Packet.features_enabled', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=360,
)


_OPENCHANNEL = _descriptor.Descriptor(
  name='OpenChannel',
  full_name='Protocol.Data.Control.OpenChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_identifier', full_name='Protocol.Data.Control.OpenChannel.channel_identifier', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel_type', full_name='Protocol.Data.Control.OpenChannel.channel_type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=435,
)


_CHANNELRESULT = _descriptor.Descriptor(
  name='ChannelResult',
  full_name='Protocol.Data.Control.ChannelResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_identifier', full_name='Protocol.Data.Control.ChannelResult.channel_identifier', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='opened', full_name='Protocol.Data.Control.ChannelResult.opened', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='common_error', full_name='Protocol.Data.Control.ChannelResult.common_error', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHANNELRESULT_COMMONERROR,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=693,
)


_KEEPALIVE = _descriptor.Descriptor(
  name='KeepAlive',
  full_name='Protocol.Data.Control.KeepAlive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_requested', full_name='Protocol.Data.Control.KeepAlive.response_requested', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=695,
  serialized_end=734,
)


_ENABLEFEATURES = _descriptor.Descriptor(
  name='EnableFeatures',
  full_name='Protocol.Data.Control.EnableFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='Protocol.Data.Control.EnableFeatures.feature', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=736,
  serialized_end=779,
)


_FEATURESENABLED = _descriptor.Descriptor(
  name='FeaturesEnabled',
  full_name='Protocol.Data.Control.FeaturesEnabled',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='Protocol.Data.Control.FeaturesEnabled.feature', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=781,
  serialized_end=825,
)

_PACKET.fields_by_name['open_channel'].message_type = _OPENCHANNEL
_PACKET.fields_by_name['channel_result'].message_type = _CHANNELRESULT
_PACKET.fields_by_name['keep_alive'].message_type = _KEEPALIVE
_PACKET.fields_by_name['enable_features'].message_type = _ENABLEFEATURES
_PACKET.fields_by_name['features_enabled'].message_type = _FEATURESENABLED
_CHANNELRESULT.fields_by_name['common_error'].enum_type = _CHANNELRESULT_COMMONERROR
_CHANNELRESULT_COMMONERROR.containing_type = _CHANNELRESULT
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.message_types_by_name['OpenChannel'] = _OPENCHANNEL
DESCRIPTOR.message_types_by_name['ChannelResult'] = _CHANNELRESULT
DESCRIPTOR.message_types_by_name['KeepAlive'] = _KEEPALIVE
DESCRIPTOR.message_types_by_name['EnableFeatures'] = _ENABLEFEATURES
DESCRIPTOR.message_types_by_name['FeaturesEnabled'] = _FEATURESENABLED

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), dict(
  DESCRIPTOR = _PACKET,
  __module__ = 'ControlChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Control.Packet)
  ))
_sym_db.RegisterMessage(Packet)

OpenChannel = _reflection.GeneratedProtocolMessageType('OpenChannel', (_message.Message,), dict(
  DESCRIPTOR = _OPENCHANNEL,
  __module__ = 'ControlChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Control.OpenChannel)
  ))
_sym_db.RegisterMessage(OpenChannel)

ChannelResult = _reflection.GeneratedProtocolMessageType('ChannelResult', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELRESULT,
  __module__ = 'ControlChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Control.ChannelResult)
  ))
_sym_db.RegisterMessage(ChannelResult)

KeepAlive = _reflection.GeneratedProtocolMessageType('KeepAlive', (_message.Message,), dict(
  DESCRIPTOR = _KEEPALIVE,
  __module__ = 'ControlChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Control.KeepAlive)
  ))
_sym_db.RegisterMessage(KeepAlive)

EnableFeatures = _reflection.GeneratedProtocolMessageType('EnableFeatures', (_message.Message,), dict(
  DESCRIPTOR = _ENABLEFEATURES,
  __module__ = 'ControlChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Control.EnableFeatures)
  ))
_sym_db.RegisterMessage(EnableFeatures)

FeaturesEnabled = _reflection.GeneratedProtocolMessageType('FeaturesEnabled', (_message.Message,), dict(
  DESCRIPTOR = _FEATURESENABLED,
  __module__ = 'ControlChannel_pb2'
  # @@protoc_insertion_point(class_scope:Protocol.Data.Control.FeaturesEnabled)
  ))
_sym_db.RegisterMessage(FeaturesEnabled)


# @@protoc_insertion_point(module_scope)
